// Solution-1.scala
// Solution to Exercise 1 in "Error Handling with Exceptions"
import com.atomicscala.AtomicTest._

/*{oldDescription}
1.	Create a method that throws an object of class Exception inside a try block. Pass the constructor for Exception a String argument. Catch the exception inside a catch clause and print the String argument.
{oldDescription}*/

// needs solution
