// Solution-7.scala
// Solution to Exercise 7 in "Error Handling with Exceptions"
import com.atomicscala.AtomicTest._

/*{oldDescription}
7.	Demonstrate that a derived-class constructor cannot catch exceptions thrown by its base-class constructor.
{oldDescription}*/

// needs solution
